// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","layout":false,"id":"1"},"2":{"path":"/maker/:resumeId","layout":false,"id":"2"},"3":{"path":"/*","layout":false,"redirect":"/","id":"3"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__Home__index" */'@/pages/Home/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Maker__index" */'@/pages/Maker/index.tsx')),
'3': React.lazy(() => import('./EmptyRoute')),
},
  };
}
